# Generated by Django 4.0.3 on 2022-04-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistory',
            name='date_last',
            field=models.DateTimeField(auto_now=True, verbose_name='последнее изучение'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='date_start',
            field=models.DateField(auto_now_add=True, verbose_name='изучается с '),
        ),
    ]
