# Generated by Django 4.0.3 on 2022-04-02 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training_room', '0002_alter_taskhistory_date_last_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_room.tasks', verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterUniqueTogether(
            name='datehistory',
            unique_together={('user', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='taskhistory',
            unique_together={('user', 'task')},
        ),
    ]
