# Generated by Django 4.0.3 on 2022-04-02 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training_room', '0003_alter_datehistory_user_alter_taskhistory_task_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskhistory',
            options={'ordering': ['-date_last', '-date_start', '-right_answers', 'wrong_answers'], 'verbose_name': 'история заданий пользователя', 'verbose_name_plural': 'истории заданий пользователей'},
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_task', models.IntegerField(default=1, verbose_name='текущий вопрос')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
    ]
