# Generated by Django 4.0.3 on 2022-04-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_room', '0004_alter_taskhistory_options_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskhistory',
            options={'ordering': ['date_last', 'date_start', 'right_answers', '-wrong_answers'], 'verbose_name': 'история заданий пользователя', 'verbose_name_plural': 'истории заданий пользователей'},
        ),
        migrations.AddField(
            model_name='profile',
            name='last_answer',
            field=models.TextField(default='', verbose_name='последний ответ'),
        ),
    ]
