# Generated by Django 4.0.3 on 2022-04-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_room', '0007_remove_datehistory_right_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='pronunciation',
            field=models.FileField(blank=True, null=True, upload_to='pronunciation/%Y/%m/%d'),
        ),
    ]
