# Generated by Django 4.0.3 on 2022-04-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_room', '0008_tasks_pronunciation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='pronunciation',
        ),
        migrations.AddField(
            model_name='tasks',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/%Y/%m/%d'),
        ),
    ]
