# Generated by Django 4.0.3 on 2022-04-04 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_room', '0010_rename_right_answers_sentences_datehistory_right_answers_sentences_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskhistory',
            options={'ordering': ['date_last'], 'verbose_name': 'история заданий пользователя', 'verbose_name_plural': 'истории заданий пользователей'},
        ),
        migrations.RenameField(
            model_name='taskhistory',
            old_name='right_answers',
            new_name='right_answers_text',
        ),
        migrations.RenameField(
            model_name='taskhistory',
            old_name='wrong_answers',
            new_name='wrong_answers_text',
        ),
    ]
