# Generated by Django 4.0.3 on 2022-04-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_room', '0011_alter_taskhistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='right_answers_audio',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='raa'),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='wrong_answers_audio',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='waa'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='right_answers_text',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='rat'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='wrong_answers_text',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='wat'),
        ),
    ]
