# Generated by Django 4.0.3 on 2022-04-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_room', '0013_alter_datehistory_right_answers_sentences_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datehistory',
            name='right_answers_sentences_audio',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='rasa'),
        ),
        migrations.AddField(
            model_name='datehistory',
            name='right_answers_words_audio',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='rawa'),
        ),
        migrations.AddField(
            model_name='datehistory',
            name='wrong_answers_sentences_audio',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='wasa'),
        ),
        migrations.AddField(
            model_name='datehistory',
            name='wrong_answers_words_audio',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='wawa'),
        ),
    ]
